# Generated by Django 2.2.4 on 2019-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190820_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
