# Generated by Django 2.2.4 on 2019-08-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190820_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
        ),
    ]
