# Generated by Django 2.2.4 on 2019-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190820_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='detected',
            name='photo',
            field=models.ImageField(default='app/facerec/detected/noimg.png', upload_to='app/facerec/detected/'),
        ),
    ]
