# Generated by Django 2.2.4 on 2019-08-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_detected_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected',
            name='photo',
            field=models.ImageField(default='app/facerec/detected/noimg.png', upload_to='detected/'),
        ),
    ]
